on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Pull
        uses: actions/checkout@v4

      - name: Get_Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Install Pyinstaller
        run: |
          pip install pyinstaller

      - name: Run Pyinstaller
        run: |
          pyinstaller --onefile -w svg_concatenate.py
      
      - name: Upload Exe file
        uses: actions/upload-artifact@v4
        with:
          name: svg_concatenate
          path: dist/svg_concatenate.exe
